package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ToDo", targetNamespace = "http://todo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDo {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getTasksByUser", targetNamespace = "http://todo/", className = "client.GetTasksByUser")
    @ResponseWrapper(localName = "getTasksByUserResponse", targetNamespace = "http://todo/", className = "client.GetTasksByUserResponse")
    public void getTasksByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getAllTasks", targetNamespace = "http://todo/", className = "client.GetAllTasks")
    @ResponseWrapper(localName = "getAllTasksResponse", targetNamespace = "http://todo/", className = "client.GetAllTasksResponse")
    public void getAllTasks();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getTasksByStatus", targetNamespace = "http://todo/", className = "client.GetTasksByStatus")
    @ResponseWrapper(localName = "getTasksByStatusResponse", targetNamespace = "http://todo/", className = "client.GetTasksByStatusResponse")
    public void getTasksByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://todo/", className = "client.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://todo/", className = "client.GetAllUsersResponse")
    public void getAllUsers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getTasksByDate", targetNamespace = "http://todo/", className = "client.GetTasksByDate")
    @ResponseWrapper(localName = "getTasksByDateResponse", targetNamespace = "http://todo/", className = "client.GetTasksByDateResponse")
    public void getTasksByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);
        
    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getTasksByPriority", targetNamespace = "http://todo/", className = "client.GetTasksByPriority")
    @ResponseWrapper(localName = "getTasksByPriorityResponse", targetNamespace = "http://todo/", className = "client.GetTasksByPriorityResponse")
    public void getTasksByPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
